-- AVERAGE ORDER PER HOUR AND DAYWEEK
SELECT HOUR,
-- ROUND(avg(TOTAL_ORDER)) AS AVG_ORDER_PER_WEEK,
ROUND(AVG(CASE WHEN WEEK = '0' THEN TOTAL_ORDER ELSE NULL END)) AS 'MONDAY',
ROUND(AVG(CASE WHEN WEEK = '1' THEN TOTAL_ORDER ELSE NULL END)) AS 'TUESDAY',
ROUND(AVG(CASE WHEN WEEK = '2' THEN TOTAL_ORDER ELSE NULL END)) AS 'WEDNESDAY',
ROUND(AVG(CASE WHEN WEEK = '3' THEN TOTAL_ORDER ELSE NULL END)) AS 'THURSDAY',
ROUND(AVG(CASE WHEN WEEK = '4' THEN TOTAL_ORDER ELSE NULL END)) AS 'FRIDAY',
ROUND(AVG(CASE WHEN WEEK = '5' THEN TOTAL_ORDER ELSE NULL END)) AS 'SATURDAY',
ROUND(AVG(CASE WHEN WEEK = '6' THEN TOTAL_ORDER ELSE NULL END)) AS 'SUNDAY'
FROM
(
SELECT date(o.order_date) as date_order,
WEEKday(O.ORDER_DATE) AS WEEK,
hOUR(O.ORDER_TIME) AS HOUR,
COUNT(distinct O.ORDER_ID) AS TOTAL_ORDER
FROM ORDERS AS O
LEFT JOIN order_details AS OD
ON O.ORDER_ID = OD.ORDER_ID
GROUP BY 1,2,3) AS DAILY_MONTHLY_ORDER
GROUP BY 1
order by 1 asc;